# Generated by Django 4.1.6 on 2023-02-11 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(max_length=20)),
                ('schedule', models.CharField(choices=[('8 AM to 9 AM', '8 AM to 9 AM'), ('9 AM to 10 AM', '9 AM to 10 AM'), ('10 AM to 11 AM', '10 AM to 11 AM'), ('11 AM to 12 PM', '11 AM to 12 PM'), ('2 PM to 3 PM', '2 PM to 3 PM'), ('3 PM to 4 PM', '3 PM to 4 PM'), ('4 PM to 5 PM', '4 PM to 5 PM'), ('5 PM to 6 PM', '5 PM to 6 PM')], max_length=20)),
                ('backup_schedule', models.CharField(blank=True, choices=[('8 AM to 9 AM', '8 AM to 9 AM'), ('9 AM to 10 AM', '9 AM to 10 AM'), ('10 AM to 11 AM', '10 AM to 11 AM'), ('11 AM to 12 PM', '11 AM to 12 PM'), ('2 PM to 3 PM', '2 PM to 3 PM'), ('3 PM to 4 PM', '3 PM to 4 PM'), ('4 PM to 5 PM', '4 PM to 5 PM'), ('5 PM to 6 PM', '5 PM to 6 PM')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=20)),
                ('card_no', models.CharField(max_length=12, null=True)),
                ('date', models.DateField(null=True)),
                ('appointed', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
