# Generated by Django 4.1.6 on 2023-02-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointed_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointed_time',
            field=models.CharField(choices=[('8 AM to 9 AM', '8 AM to 9 AM'), ('9 AM to 10 AM', '9 AM to 10 AM'), ('10 AM to 11 AM', '10 AM to 11 AM'), ('11 AM to 12 PM', '11 AM to 12 PM'), ('2 PM to 3 PM', '2 PM to 3 PM'), ('3 PM to 4 PM', '3 PM to 4 PM'), ('4 PM to 5 PM', '4 PM to 5 PM'), ('5 PM to 6 PM', '5 PM to 6 PM')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booked_date',
            field=models.DateField(null=True),
        ),
    ]
